#
# ps8pr2.py  (Problem Set 8, Problem 2)
#
# Markov text generation       
#

import random

# Function 1
def create_dictionary(filename):
    """ returns a dictionary of key-value pairs in which:
        each key is a word encountered in the text file and
        the corresponding value is a list of words that follow 
        the key word in the text file """
    file = open(filename, 'r')
    text = file.read()
    file.close()
   
    words = text.split()
    d = {}
    current_word = '$'
    
    for word in words:
        if current_word not in d:
            d[current_word] = [word]
        else:
            d[current_word] += [word]
        if word[-1] in '.?!':
            current_word = '$'
        else:
            current_word = word
            
    return d

# Function 2
def generate_text(word_dict, num_words):
    """ takes as parameters a dictionary of word transitions 
        (generated by the create_dictionary function) named 
        word_dict and a positive integer named num_words. """
    current_word = '$'
    
    for i in range(num_words):
        wordlist = word_dict[current_word]
        next_word = random.choice(wordlist)
        print(next_word, end=' ')
    
    if next_word[-1] in '.?!':
        current_word = '$'
    else:
        current_word = next_word

